name: Wildberries Telegram Bot

on:
  schedule:
    # Запускается каждые 2 часа с 07:30 UTC (это 10:30 МСК) до 16:30 UTC (19:30 МСК)
    - cron: '30 4 * * *'  # 07:30 MSK
    - cron: '30 6 * * *'  # 09:30 MSK
    - cron: '30 8 * * *'  # 11:30 MSK
    - cron: '30 10 * * *' # 13:30 MSK
    - cron: '30 12 * * *' # 15:30 MSK
    - cron: '30 14 * * *' # 17:30 MSK
    - cron: '30 16 * * *' # 19:30 MSK

  workflow_dispatch:  # ручной запуск

jobs:
  send-report:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # безопасность

    steps:
      - name: 📥 Клонируем репозиторий
        uses: actions/checkout@v3

      - name: 🐍 Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Устанавливаем зависимости
        run: pip install requests

      - name: 🚀 Запуск скрипта
        run: python script.py
        env:
          WB_TOKEN: ${{ secrets.WB_TOKEN }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
