name: Wildberries Telegram Bot

on:
  schedule:
    # Каждый час с 07:30 до 16:30 UTC (10:30 - 19:30 МСК)
        - cron: '30 4 * * *'  # 07:30 MSK
        - cron: '30 5 * * *'  # 08:30 MSK
        - cron: '30 6 * * *'  # 09:30 MSK
        - cron: '30 7 * * *'  # 10:30 MSK
        - cron: '30 8 * * *'  # 11:30 MSK
        - cron: '30 9 * * *'  # 12:30 MSK
        - cron: '30 10 * * *' # 13:30 MSK
        - cron: '30 11 * * *' # 14:30 MSK
        - cron: '30 12 * * *' # 15:30 MSK
        - cron: '30 13 * * *' # 16:30 MSK
        - cron: '30 14 * * *' # 17:30 MSK
        - cron: '30 15 * * *' # 18:30 MSK
        - cron: '30 16 * * *' # 19:30 MSK
        - cron: '30 17 * * *' # 20:30 MSK

  workflow_dispatch:  # ручной запуск

jobs:
  send-report:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: 📥 Клонируем репозиторий
        uses: actions/checkout@v3

      - name: 🐍 Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Устанавливаем зависимости
        run: pip install requests

      - name: 🚀 Запуск скрипта
        run: python API_bulder.py
        env:
          WB_TOKEN: ${{ secrets.WB_TOKEN }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
