name: Telegram Report Bot

on:
  schedule:
    - cron: '0 5 * * *'   # 08:00 MSK
    - cron: '0 7 * * *'   # 10:00 MSK
    - cron: '0 9 * * *'   # 12:00 MSK
    - cron: '0 11 * * *'  # 14:00 MSK
    - cron: '0 13 * * *'  # 16:00 MSK
    - cron: '0 15 * * *'  # 18:00 MSK
    - cron: '40 16 * * *'  # 20:00 MSK

  workflow_dispatch:  # запуск вручную

jobs:
  send-report:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Клонируем репозиторий
        uses: actions/checkout@v3

      - name: 🐍 Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Устанавливаем зависимости (если появятся)
        run: pip install requests

      - name: 🚀 Запуск скрипта
        run: python API_bulder.py

        env:
          WB_TOKEN: ${{ secrets.WB_TOKEN }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
